version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5673:5672
      - 15673:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - backend_implementation
  producer:
    build: .
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - INTERVAL_MS=5000
      - QUEUE_NAME=message_queue
    depends_on:
      - rabbitmq
  consumer:
    build: .
    command: nodemon consumer.js
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
      - QUEUE_NAME=message_queue
    depends_on:
      - rabbitmq
networks:
  backend_implementation:
    driver: bridge
